[package]
name = "roxy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "roxy"

[dependencies]
actix-web = "4.9.0"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.133", features = ["raw_value"] }
tokio = { version = "1.41.1", features = ["full"] }